services:
  db:
    image: postgres:15
    container_name: hris-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hris_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hris-backend
    restart: always
    env_file: .env
    ports:
      - '4000:4000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hris-frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
          - ./frontend:/app     # mount your source code
          - /app/node_modules   # prevent node_modules from being overwritten
    working_dir: /app
    environment:
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true   # Fix for file watching inside Docker (esp. on Windows/macOS)
    depends_on:
      - backend

volumes:
  postgres-data:
