services:
  db:
    image: postgres:15
    container_name: hris-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hris_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hris-backend
    restart: always
    env_file: .env
    ports:
      - '4000:4000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hris-frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres-data:
