import { UserRole } from '../../users/entities/user.entity';
import { ALL_PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.ADMIN]: Object.values(ALL_PERMISSIONS), // Admin has all permissions
  
  [UserRole.HR]: [
    // User Management
    ALL_PERMISSIONS.CREATE_USER,
    ALL_PERMISSIONS.READ_USER,
    ALL_PERMISSIONS.UPDATE_USER,
    ALL_PERMISSIONS.LIST_USERS,
    
    // Employee Management
    ALL_PERMISSIONS.CREATE_EMPLOYEE,
    ALL_PERMISSIONS.READ_EMPLOYEE,
    ALL_PERMISSIONS.UPDATE_EMPLOYEE,
    ALL_PERMISSIONS.LIST_EMPLOYEES,
    ALL_PERMISSIONS.VIEW_SALARY,
    ALL_PERMISSIONS.UPDATE_SALARY,
    ALL_PERMISSIONS.VIEW_PERFORMANCE,
    ALL_PERMISSIONS.UPDATE_PERFORMANCE,
    
    // Department Management
    ALL_PERMISSIONS.READ_DEPARTMENT,
    ALL_PERMISSIONS.LIST_DEPARTMENTS,
    
    // Leave Management
    ALL_PERMISSIONS.READ_LEAVE_REQUEST,
    ALL_PERMISSIONS.APPROVE_LEAVE_REQUEST,
    ALL_PERMISSIONS.REJECT_LEAVE_REQUEST,
    ALL_PERMISSIONS.LIST_LEAVE_REQUESTS,
    ALL_PERMISSIONS.VIEW_LEAVE_BALANCE,
    
    // Payroll
    ALL_PERMISSIONS.GENERATE_PAYROLL,
    ALL_PERMISSIONS.READ_PAYROLL,
    ALL_PERMISSIONS.APPROVE_PAYROLL,
    ALL_PERMISSIONS.LIST_PAYROLL,
    ALL_PERMISSIONS.VIEW_PAYROLL_REPORTS,
  ],
  
  [UserRole.MANAGER]: [
    // Employee Management (own team)
    ALL_PERMISSIONS.READ_EMPLOYEE,
    ALL_PERMISSIONS.UPDATE_EMPLOYEE,
    ALL_PERMISSIONS.LIST_EMPLOYEES,
    ALL_PERMISSIONS.VIEW_PERFORMANCE,
    ALL_PERMISSIONS.UPDATE_PERFORMANCE,
    
    // Department Management
    ALL_PERMISSIONS.READ_DEPARTMENT,
    ALL_PERMISSIONS.LIST_DEPARTMENTS,
    
    // Leave Management (own team)
    ALL_PERMISSIONS.READ_LEAVE_REQUEST,
    ALL_PERMISSIONS.APPROVE_LEAVE_REQUEST,
    ALL_PERMISSIONS.REJECT_LEAVE_REQUEST,
    ALL_PERMISSIONS.LIST_LEAVE_REQUESTS,
    ALL_PERMISSIONS.VIEW_LEAVE_BALANCE,
    
    // Payroll (own team)
    ALL_PERMISSIONS.READ_PAYROLL,
    ALL_PERMISSIONS.LIST_PAYROLL,
  ],
  
  [UserRole.EMPLOYEE]: [
    // Self management
    ALL_PERMISSIONS.READ_USER,
    ALL_PERMISSIONS.UPDATE_USER,
    
    // Own employee data
    ALL_PERMISSIONS.READ_EMPLOYEE,
    
    // Leave Management (own requests)
    ALL_PERMISSIONS.CREATE_LEAVE_REQUEST,
    ALL_PERMISSIONS.READ_LEAVE_REQUEST,
    ALL_PERMISSIONS.UPDATE_LEAVE_REQUEST,
    ALL_PERMISSIONS.DELETE_LEAVE_REQUEST,
    ALL_PERMISSIONS.VIEW_LEAVE_BALANCE,
    
    // Own payroll
    ALL_PERMISSIONS.READ_PAYROLL,
  ],
}; 